#!/bin/bash
set -xe
apt update
export DEBIAN_FRONTEND=noninteractive
apt upgrade -y
apt install -y openjdk-7-jdk \
	git-core gnupg flex bison gperf build-essential \
	zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 \
	lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev ccache \
	libgl1-mesa-dev libxml2-utils xsltproc unzip \
	make python-networkx \
	syslog-ng-core autotools-dev pkg-config libtool vim bc bash-completion
apt-get clean

# Clean up APT when done.
rm -rf /tmp/* /var/tmp/*
