#!/bin/bash
set -xe

export HOME=/root
ssh-keygen -R gitlab.hopebaytech.com
ssh-keygen -R 10.10.99.200
ssh-keygen -R gitlab.hopebaytech.com,10.10.99.200
ssh-keyscan -H gitlab.hopebaytech.com,10.10.99.200 >> ~/.ssh/known_hosts
ssh-keyscan -H 10.10.99.200 >> ~/.ssh/known_hosts
ssh-keyscan -H gitlab.hopebaytech.com >> ~/.ssh/known_hosts
