#!/bin/bash


sda=`cat /proc/mdstat | grep sda`
sdb=`cat /proc/mdstat | grep sdb`
new_disk=""

if [ -z "$sda" ] && [ -n "$sdb" ]; then
    echo "sda is a new disk!"
    sfdisk -d /dev/sdb > /tmp/partition
    sfdisk /dev/sda < /tmp/partition
    unlink /tmp/partition
    new_disk="/dev/sda"
elif [ -n "$sda" ] && [ -z "$sdb" ]; then
    echo "sdb is a new disk!"
    sfdisk -d /dev/sda > /tmp/partition
    sfdisk /dev/sdb < /tmp/partition
    unlink /tmp/partition
    new_disk="/dev/sdb"
else
    echo "No new disk!"
    exit 0
fi

echo "new disk name is $new_disk!"

mdadm --zero-superblock $new_disk"1"
mdadm --zero-superblock $new_disk"2"
partprobe
mdadm --add /dev/md0 $new_disk"1" 
mdadm --add /dev/md1 $new_disk"2" 

