#!/bin/bash


echo "===start check raid1!"
echo "===check which disk is new!"
sda=`mdadm --detail /dev/md0 | grep sda`
sdb=`mdadm --detail /dev/md0 | grep sdb`
new_disk=""

if [ -z "$sda" ] && [ -n "$sdb" ]; then
    echo "===sda is a new disk!"
    new_disk="/dev/sda"
    old_disk="/dev/sdb"
elif [ -n "$sda" ] && [ -z "$sdb" ]; then
    echo "===sdb is a new disk!"
    new_disk="/dev/sdb"
    old_disk="/dev/sda"
else
    echo "===No new disk!"
    exit 0
fi

echo "===new disk name is $new_disk!"
echo "===do sfdisk partition rebuild!"
sfdisk -d "$old_disk" > /tmp/partition
sfdisk --force --no-reread "$new_disk" < /tmp/partition
echo "===write partprobe!"
partprobe
echo "unlink partition info file"
unlink /tmp/partition
echo "===do zero superblock to $new_disk!"
mdadm --zero-superblock $new_disk"1"
mdadm --zero-superblock $new_disk"2"
echo "add $new_disk to md0 and md1"
mdadm --add /dev/md0 $new_disk"1" 
mdadm --add /dev/md1 $new_disk"2" 
