#!/bin/sh
CACHE_DIR="/storage/http_proxy_cache/"
CONFDIR="/etc/delta"
SRCDIR="/tmp/DCloudGateway"
#~ PY_PATH="/usr/local/lib/python2.7/dist-packages/"

### 1. setup python search path
#~ cat > $PY_PATH/gatewayapi.pth << EOF
#~ $PY_PATH/DCloudGateway
#~ EOF

### 2. setup config file
mkdir -p $CACHE_DIR
bash $SRCDIR/src/http_proxy/gen_squid3_conf.sh
chmod 777  $CACHE_DIR
echo "Squid3 configuration has been written."

### 3. Restart Squid3 service
service squid3 restart

# add double check for squid3 cache directory at each power on.
cat >/etc/init.d/make_http_proxy_cache_dir <<EOF
mkdir -p $CACHE_DIR
chmod 777 $CACHE_DIR
EOF
chmod 777 /etc/init.d/make_http_proxy_cache_dir
cp -rs /etc/init.d/make_http_proxy_cache_dir /etc/rc2.d/S29make_http_proxy_cache_dir
echo "    Squid3 configuration has been written."

# config nfs service
ln -s /usr/lib/insserv/insserv /sbin/insserv
chkconfig --level 2345 nfs-kernel-server off

# setup gateway api
cd /tmp/DCloudGateway/
python setup.py install

# install configuration files
if [ ! -e $CONFDIR/update_bandwidth ]; then
    cp $SRCDIR/config/rc.local /etc
    cp $SRCDIR/config/crontab /etc
    chmod 600 /etc/crontab
    bash $SRCDIR/gateway_scripts/createSmbUser.sh superuser
    chmod 666 $CONFDIR/Gateway.ini
    cp $SRCDIR/config/interfaces /etc/network/interfaces
    cp $SRCDIR/config/hosts.allow /etc
    cp $SRCDIR/config/gw_schedule.conf $CONFDIR/
    cp $SRCDIR/config/smb.orig $CONFDIR
    cp $SRCDIR/gateway_scripts/hourly_run_this $CONFDIR
    cp $SRCDIR/gateway_scripts/daily_run_this /etc/cron.daily/
    cp $SRCDIR/gateway_scripts/update_bandwidth $CONFDIR
    cp $SRCDIR/gateway_scripts/python_code/* $CONFDIR
    cp $SRCDIR/gateway_scripts/shaping_port_8080.sh $CONFDIR
    cp $SRCDIR/gateway_scripts/uploadon $CONFDIR
    cp $SRCDIR/gateway_scripts/uploadoff $CONFDIR
    cp $SRCDIR/gateway_scripts/check_expired $CONFDIR
    cp $SRCDIR/gateway_scripts/post-gwstart.conf /etc/init/
    cp $SRCDIR/gateway_scripts/check-gwstart.conf /etc/init/
    cp $SRCDIR/gateway_scripts/reorder_eth.conf /etc/init/
    cp $SRCDIR/gateway_scripts/nmbd.conf /etc/init/
    cp $SRCDIR/gateway_scripts/smbd.conf /etc/init/
    cp $SRCDIR/gateway_scripts/delete_lostfound.conf /etc/init/
    cp $SRCDIR/config/sudoers_delta /etc/sudoers.d/
    cp $SRCDIR/config/nfs-kernel-server /etc/default/nfs-kernel-server

    #-- Ovid Wu <ovid.wu@delta.com.tw> Wed, 01 Aug 2012 05:34:41 +0000
    # the permission of sudoers_delta is required 0440
    chmod 0440 /etc/sudoers.d/sudoers_delta
    cp $SRCDIR/gateway_scripts/gw-bg-tasks.conf /etc/init/
    #os.system("cp config/smb.conf %s/"%SMBDIR)
    cp $SRCDIR/gateway_scripts/snapshot_bot $CONFDIR
    cp $SRCDIR/gateway_scripts/snapshot_check $CONFDIR
    cp $SRCDIR/gateway_scripts/wait_network_up $CONFDIR
    cp $SRCDIR/gateway_scripts/wait_gateway_up $CONFDIR
    cp $SRCDIR/gateway_scripts/service_restart $CONFDIR
    cp $SRCDIR/gateway_scripts/hourly_snapshotting $CONFDIR
    cp $SRCDIR/gateway_scripts/run_background_tasks $CONFDIR
    cp $SRCDIR/gateway_scripts/reorder_eth.sh $CONFDIR
    cp $SRCDIR/gateway_scripts/delete_lostfound $CONFDIR
    rm -rf /root/.s3ql/*
    chmod -R 777 /root
    chown -R www-data:www-data $CONFDIR
    cp -rs /usr/bin/*s3ql* /usr/local/bin
fi


# clean up temp codes
rm -r $SRCDIR
