#!/bin/bash
#########################################################################
#
# Copyright © 2015-2016 Hope Bay Technologies, Inc. All rights reserved.
#
# Abstract:
#
# Revision History
#   2016/1/18 Jethro unified usage of workspace path
#
##########################################################################
if [ "$UID" -ne 0 ]; then exec sudo -E ${BASH_SOURCE[0]}; fi
echo -e "\n======== ${BASH_SOURCE[0]} ========"
repo="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && while [ ! -d utils ] ; do cd ..; done; pwd )"
source $repo/utils/common_header.bash

sed -r -i"" "s/archive.ubuntu.com/10.0.1.5:8001/" /etc/apt/sources.list

packages+=" cmake git build-essential"	# Required by oclint / bear
packages+=" openjdk-7-jdk wget unzip"	# Required by PMD for CPD(duplicate code)
packages+=" cloc"						# Install cloc for check code of line
packages+=" mono-complete wget unzip"	# Required mono and CCM for complexity
packages+=" clang-3.5"					# clang Scan Build Reports
packages+=" colormake"					# colorful logs
packages+=" parallel"					# parallel check source code style

install_pkg
apt-get clean || :
