#!/bin/bash
#########################################################################
#
# Copyright © 2015-2016 Hope Bay Technologies, Inc. All rights reserved.
#
# Abstract:
#
# Revision History
#   2016/1/18 Jethro unified usage of workspace path
#
##########################################################################

echo -e "\n======== ${BASH_SOURCE[0]} ========"
repo="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && while [ ! -d .git ] ; do cd ..; done; pwd )"
here="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $repo/utils/common_header.bash
cd $repo

sudo git clean -dXf
pwd
whoami
ls -la

srcdir=$repo/src/HCFS
testdir=$repo/tests

# Install dependencies
$repo/utils/setup_dev_env.sh -vm unit_test
# Speedup compiling
. $repo/utils/env_config.sh
sudo chown -R $USER:$USER $HOME/.ccache || :

# oclint-report.xml
#       OCLint with Bear
bear make -j4 -C $srcdir
/oclint-0.8.1/bin/oclint-json-compilation-database . -- -report-type pmd -o $repo/oclint-report.xml || :
sed -i "s@file name=\"@&src/HCFS/@g" $repo/oclint-report.xml

# cpd-result.xml
#        PMD's Copy/Paste Detector (CPD)
/pmd-bin-5.2.2/bin/run.sh cpd --minimum-tokens 100 --encoding UTF-8 --files $srcdir --format xml --language cpp > $repo/cpd-result.xml || return_code=$?
if [[ "$return_code" != "" && "$return_code" != 4 ]]; then
	echo pmd returns unknown error code $return_code
	false
fi
sed -i "s@$repo/@@g" $repo/cpd-result.xml

# Run unit test
cd $testdir/unit_test
./run_unittests

ccache -s $HOME/.ccache

# cloc-result.xml
#        Publish SLOCCount analysis results
cloc --by-file --xml --out=$repo/cloc-result.xml $srcdir
sed -i "s@$repo/@@g" $repo/cloc-result.xml

# ccm-result.xml
#        Publish CCM analysis results (Cyclomatic Complexity)
mono /CCM.exe $srcdir /xml > $repo/ccm-result.xml
sed -i "s@<file>/@<file>src/HCFS/@g" $repo/ccm-result.xml

# hb_clint.xml
#         Cehck code style
find $srcdir -name "*.c" -or -name "*.cpp" | parallel --jobs 4 $testdir/code_checking/hb_clint.py {} >& $repo/hb_clint.xml || :
sed -i "s@$repo/@@g" $repo/hb_clint.xml

# checkpatch - No report
#         Cehck code style
#$testdir/code_checking/checkpatch.pl --terse --no-tree --no-signoff -f `find $srcdir -name '*.[ch]'` || :
find $srcdir -name "*.c" -or -name "*.cpp" | parallel --jobs 4 $testdir/code_checking/checkpatch.pl --terse --no-tree --no-signoff -f {} || :

# clangScanBuildReports/
#         Clang Scan-Build Results
rm -rf ${repo}/clangScanBuildReports
cd $srcdir
make clean
scan-build-3.5 -o ${repo}/clangScanBuildReports make -j4

# coverage.xml
#         Unit test coverage report
cd $testdir/unit_test
gcovr -x -r $srcdir . > $repo/coverage.xml
sed -i "s@$repo/@@g" $repo/coverage.xml
gcovr -r $srcdir .
