#!/bin/sh
#
# THIS SCRIPT RUN CHECK ON `HCFS_ANDROID_000_03`
#
# **NOTE**
# MODIFY THE SERVER, USER, KEY, BUCKET FOR SCRIP TO WORK


SERVER="https://172.16.40.117:8080/auth/v1.0"
#SERVER="https://61.219.202.83/auth/v1.0"
USER="005NF8YBSPQI:005NF8YBSPQI"
KEY="bMYGisntATZA"
BUCKET="N2BUIEPHL30288TY5HJ5ZN9RPEXBYZK2E5FB7II9F9K74BZMCAUSG83TSPLL7B3I99U9ASLF6I7DDI6GQH7HFXZKMN56YCG28WFCYFWGL969MGA6WZ6VILEMFC33MWPO"

adb root
adb pull /sdcard/datablock.backup
inode=$(adb shell ls -i /sdcard/datablock | awk '{print $1}')
nameOnCloud=$(swift --insecure -A ${SERVER} -U ${USER} -K ${KEY} list ${BUCKET} --prefix data_${inode})
echo Downloding inode $inode \(${nameOnCloud}\)...
swift --insecure -A ${SERVER} -U ${USER} -K ${KEY} download ${BUCKET} ${nameOnCloud} -o datablock.cloud
diff datablock.cloud datablock.backup
