#! /bin/sh
### BEGIN INIT INFO
# Provides:             swift-event-manager
# Required-Start:       $remote_fs $syslog
# Required-Stop:        $remote_fs $syslog
# Should-Start:         $local_fs
# Should-Stop:          $local_fs
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Start swift-event-manager daemon
# Description:          Start up swift-event-manager, a daemon receiving and handling events from the cluster
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/local/bin/swift-event-manager
NAME=swift-event-manager
DESC=swift-event-manager

test -f $DAEMON || exit 0

set -e

case "$1" in
 start)
    echo -n "Starting $DESC...\n"
    python $DAEMON start
    if [ $? = 0 ]; then
        echo -n "OK!\n"
    else
        echo -n "Failed to start daemon!\n"
    fi
    ;;
 stop)
    echo -n "Stopping $DESC...\n"
    python $DAEMON stop
    if [ $? = 0 ]; then
        echo -n "Daemon seems to have stopped.\n"
    else
        echo -n "Failed to stop daemon!\n"
    fi
    ;;
 restart|force-reload)
    #
    #    If the "reload" option is implemented, move the "force-reload"
    #    option to the "reload" entry above. If not, "force-reload" is
    #    just the same as "restart".
    #
    echo -n "Restarting $DESC...\n"
    python $DAEMON restart
    if [ $? = 0 ]; then
        echo -n "OK.\n"
    else
        echo -n "Failed to restart daemon!\n"
    fi
    ;;
 *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop|restart|force-reload}" >&2
    exit 1
    ;;
esac

exit 0
