#! /bin/bash
# Command for deploy Zone Config Wizard (ZCW).
# Delta Electronics, Inc. 2012

ARGV="$@"

case $ARGV in
start)
	/etc/init.d/apache2-zcw start
	/etc/init.d/celeryd start
	;;
stop)
	/etc/init.d/apache2-zcw stop
	/etc/init.d/celeryd stop
	;;
restart)
	/etc/init.d/apache2-zcw restart
	/etc/init.d/celeryd restart
    ;;
"service start")
	/etc/init.d/apache2-zcw start
	/etc/init.d/celeryd start
	update-rc.d apache2-zcw defaults
	update-rc.d celeryd defaults
    ;;
"service stop")
	/etc/init.d/apache2-zcw stop
	/etc/init.d/celeryd stop
	update-rc.d -f apache2-zcw remove
	update-rc.d -f celeryd remove
	;;
*)
    echo $ARGV
esac

exit 0
