#!/bin/bash
#########################################################################
#
# Copyright © 2015-2016 Hope Bay Technologies, Inc. All rights reserved.
#
# Abstract:
#
# Revision History
#   2016/1/18 Jethro unified usage of workspace path
#
##########################################################################
if [ "$UID" -ne 0 ]; then exec sudo -E ${BASH_SOURCE[0]}; fi
echo -e "\n======== ${BASH_SOURCE[0]} ========"
repo="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && while [ ! -d .git ] ; do cd ..; done; pwd )"
here="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $repo/utils/common_header.bash
cd $repo

if [ ! -f /.dockerinit ]; then
	exit
fi

OLDUID=${SUDO_UID:-$UID}
OLDGID=${SUDO_GID:-$GROUPS}
NEWUID=$(stat -c '%u' $repo)
NEWGID=$(stat -c '%g' $repo)
# Only fix file permission if thry are different then expect
if [[ ( $NEWUID != 0 ) && ( $OLDUID != $NEWUID || $OLDGID != $NEWGID ) ]]; then
	echo FIX file permission in docker
	ls -l $repo
	if [ $NEWUID -eq 0 ]; then
		NEWUID=$OLDUID
	else
		sudo usermod -u $NEWUID jenkins
	fi
	if [ $NEWGID -eq 0 ]; then
		NEWGID=$OLDGID
	else
		sudo groupmod -g $NEWGID jenkins
	fi
	sudo chown -R $NEWUID:$NEWGID $repo
	ls -l $repo
fi

