#!/bin/sh
CACHE_DIR="/storage/http_proxy_cache/"
CONFDIR="/etc/delta"
SRCDIR="/tmp/DCloudGateway"
#~ PY_PATH="/usr/local/lib/python2.7/dist-packages/"

### 1. setup python search path
#~ cat > $PY_PATH/gatewayapi.pth << EOF
#~ $PY_PATH/DCloudGateway
#~ EOF

# 1. append apt-server domain name
echo "        ***** append APT-server to /etc/apt/sources.list.d/ *****"
cat >/etc/apt/sources.list.d/delta-server-precise.list <<EOF
deb http://apt.delcloudia.com/packages/ubuntu/ precise main
deb-src http://apt.delcloudia.com/packages/ubuntu precise main
deb file:// /var/cache/apt/archives/
EOF

### 2. setup config file
mkdir -p $CACHE_DIR
bash $SRCDIR/src/http_proxy/gen_squid3_conf.sh $CACHE_DIR
chmod 777  $CACHE_DIR
echo "Squid3 configuration has been written."

### 3. Restart Squid3 service
service squid3 restart

# add double check for squid3 cache directory at each power on.
cat >/etc/init.d/make_http_proxy_cache_dir <<EOF
mkdir -p $CACHE_DIR
chmod 777 $CACHE_DIR
EOF
chmod 777 /etc/init.d/make_http_proxy_cache_dir
cp -rf -rs /etc/init.d/make_http_proxy_cache_dir /etc/rc2.d/S29make_http_proxy_cache_dir
echo "    Squid3 configuration has been written."

# config nfs service
ln -s /usr/lib/insserv/insserv /sbin/insserv
chkconfig --level 2345 nfs-kernel-server off

# setup gateway api
cd /tmp/DCloudGateway/
python setup.py install

# install configuration files
if [ ! -e $CONFDIR/update_bandwidth ]; then
    cp -rf $SRCDIR/config/rc.local /etc
    cp -rf $SRCDIR/config/crontab /etc
    chmod 600 /etc/crontab
    bash $SRCDIR/gateway_scripts/createSmbUser.sh superuser
    chmod 666 $CONFDIR/Gateway.ini
    cp -rf $SRCDIR/config/interfaces /etc/network/interfaces
    cp -rf $SRCDIR/config/hosts.allow /etc
    cp -rf $SRCDIR/config/hosts.deny /etc
    #~ cp -rf $SRCDIR/config/exports /etc	#~ take out this for avoiding asking "keep local version"
    cp -rf $SRCDIR/config/sysctl.conf /etc
    cp -rf $SRCDIR/config/gw_schedule.conf $CONFDIR/
    cp -rf $SRCDIR/config/savebox.ini $CONFDIR/
    #cp -rf $SRCDIR/config/smb.orig $CONFDIR
    cp -rf $SRCDIR/gateway_scripts/hourly_run_this /etc/cron.hourly/
    cp -rf $SRCDIR/gateway_scripts/daily_run_this /etc/cron.daily/
    cp -rf $SRCDIR/gateway_scripts/update_bandwidth $CONFDIR
    cp -rf $SRCDIR/gateway_scripts/python_code/*.py $CONFDIR
    cp -rf $SRCDIR/gateway_scripts/shaping_port_8080.sh $CONFDIR
    cp -rf $SRCDIR/gateway_scripts/uploadon $CONFDIR
    cp -rf $SRCDIR/gateway_scripts/uploadoff $CONFDIR
    cp -rf $SRCDIR/gateway_scripts/check_expired $CONFDIR
    cp -rf $SRCDIR/gateway_scripts/post-gwstart.conf /etc/init/
    cp -rf $SRCDIR/gateway_scripts/check-gwstart.conf /etc/init/
    cp -rf $SRCDIR/gateway_scripts/nic.conf /etc/init/  # fixed at 2012/10/15
    cp -rf $SRCDIR/gateway_scripts/reorder_eth.sh /etc/delta/ # fixed at 2012/10/15
    cp -rf $SRCDIR/gateway_scripts/nmbd.conf /etc/init/
    cp -rf $SRCDIR/gateway_scripts/smbd.conf /etc/init/
    cp -rf $SRCDIR/gateway_scripts/delete_lostfound.conf /etc/init/
    cp -rf $SRCDIR/gateway_scripts/upgrade_failover /etc/init.d/  # Yen added at 2012/10/31
    cp -rf -rs /etc/init.d/upgrade_failover /etc/rc2.d/S05upgrade_failover  # Yen added at 2012/10/31
    cp -rf $SRCDIR/config/sudoers_delta /etc/sudoers.d/
    cp -rf $SRCDIR/config/nfs-kernel-server /etc/default/nfs-kernel-server
    cp -rf $SRCDIR/gateway_scripts/showlog /usr/bin/  # Yen added at 2012/11/16

    #-- Ovid Wu <ovid.wu@delta.com.tw> Wed, 01 Aug 2012 05:34:41 +0000
    # the permission of sudoers_delta is required 0440
    chmod 0440 /etc/sudoers.d/sudoers_delta
    cp -rf $SRCDIR/gateway_scripts/gw-bg-tasks.conf /etc/init/
    #os.system("cp -rf config/smb.conf %s/"%SMBDIR)
    cp -rf $SRCDIR/gateway_scripts/snapshot_bot $CONFDIR
    cp -rf $SRCDIR/gateway_scripts/snapshot_check $CONFDIR
    cp -rf $SRCDIR/gateway_scripts/wait_network_up $CONFDIR
    cp -rf $SRCDIR/gateway_scripts/wait_gateway_up $CONFDIR
    cp -rf $SRCDIR/gateway_scripts/service_restart $CONFDIR
    cp -rf $SRCDIR/gateway_scripts/hourly_snapshotting $CONFDIR
    cp -rf $SRCDIR/gateway_scripts/run_background_tasks $CONFDIR
    cp -rf $SRCDIR/gateway_scripts/reorder_eth.sh $CONFDIR
    cp -rf $SRCDIR/gateway_scripts/delete_lostfound $CONFDIR
    rm -rf /root/.s3ql/*
    chmod -R 777 /root
    chown -R www-data:www-data $CONFDIR
    cp -rs /usr/bin/*s3ql* /usr/local/bin
fi

