#!/bin/sh
CACHE_DIR="/storage/http_proxy_cache/"

### 2. setup config file
mkdir -p $CACHE_DIR
bash /tmp/DCloudGateway/src/http_proxy/gen_squid3_conf.sh
chmod 777  $CACHE_DIR
echo "Squid3 configuration has been written."

### 3. Restart Squid3 service
service squid3 restart

# add double check for squid3 cache directory at each power on.
cat >/etc/init.d/make_http_proxy_cache_dir <<EOF
mkdir -p $CACHE_DIR
chmod 777 $CACHE_DIR
EOF
chmod 777 /etc/init.d/make_http_proxy_cache_dir
cp -rs /etc/init.d/make_http_proxy_cache_dir /etc/rc2.d/S29make_http_proxy_cache_dir
echo "    Squid3 configuration has been written."

# setup gateway api
cd /tmp/DCloudGateway/
python setup.py install

ln -s /usr/lib/insserv/insserv /sbin/insserv
chkconfig --level 2345 nfs-kernel-server off
