if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
	. /etc/bash_completion
fi

cd /data
source /data/build/envsetup.sh
set -x
alias buildud='cd /data; ./build.sh -s s58a_aap_gen1 -v userdebug'
alias buildu='cd /data; ./build.sh -s s58a_aap_gen1 -v user'
set +x
