#!/bin/bash
# detect any failed upgrade 
STATUS_FILE="/var/log/gateway_upgrade.status"
UPGRADE_STATUS=`cat $STATUS_FILE`

logger "start executing /etc/init.d/do_gateway_upgrade"

if [ "$UPGRADE_STATUS" == "9" ]
then
    echo "Upgrade Gateway."
    #/etc/delta/LED_controller.sh 1
    apt-get remove -y --force-yes dcloud-gateway dcloudgatewayapi s3ql
    apt-get update
    apt-get install -y --force-yes dcloud-gateway dcloudgatewayapi s3ql
    if [ $? != 0 ]; then
        #/etc/delta/LED_controller.sh 2
        exit $?
    fi
    apt-get install --reinstall -y --force-yes savebox
    if [ $? != 0 ]; then
        #/etc/delta/LED_controller.sh 2
        exit $?
    fi
    ## change upgrade status
    echo '1' > $STATUS_FILE     ## 1 = NO_UPGRADE_AVAILABLE
    #/etc/delta/LED_controller.sh 2
fi

logger "finish executing /etc/init.d/do_gateway_upgrade"
