# Use phusion/baseimage as base image. To make your builds reproducible, make
# sure you lock down to a specific version, not to `latest`!
# See https://github.com/phusion/baseimage-docker/blob/master/Changelog.md for
# a list of version numbers.
FROM docker:5000/s58a-buildbox:source-only

# Use baseimage-docker's init system.
#CMD ["/sbin/my_init"]

WORKDIR /data
RUN yes | ./build.sh -s s58a_aap_gen1 -v user
