#!/bin/bash

CURPATH=$PWD
cd c/unittest_modules/utils/
rm *.gcda
rm *.gcov
rm *.gcno
make clean
make
./utils_unittest
cd $CURPATH
cd c/unittest_modules/meta_mem_cache/
rm *.gcda
rm *.gcov
rm *.gcno
make clean
make
./meta_mem_cache_unittest
cd $CURPATH
cd c/unittest_modules/fuseop/
rm *.gcda
rm *.gcov
rm *.gcno
make clean
make
./fuseop_unittest
cd $CURPATH
gcovr -r ../../src/HCFS/
