#!/bin/bash
echo ======== ${BASH_SOURCE[0]} ========
set -e -x
OLDUID=${SUDO_UID:-$UID}
OLDGID=${SUDO_GID:-$GROUPS}
NEWUID=$(stat -c '%u' /home/jenkins/workspace/HCFS)
NEWGID=$(stat -c '%g' /home/jenkins/workspace/HCFS)
if [[ $OLDUID != $NEWUID || $OLDGID != $NEWGID ]]; then
	echo FIX file permission in docker
	ls -l /home/jenkins/workspace/HCFS
	if [ $NEWUID -eq 0 ]; then
		NEWUID=$OLDUID
	else
		sudo usermod -u $NEWUID jenkins
	fi
	if [ $NEWGID -eq 0 ]; then
		NEWGID=$OLDGID
	else
		sudo groupmod -g $NEWGID jenkins
	fi
	sudo chown -R $NEWUID:$NEWGID $HOME
	ls -l /home/jenkins/workspace/HCFS
fi
