#!/bin/bash
echo ======== ${BASH_SOURCE[0]} ========
echo docker-unittest-stylecheck-slave environment is required
export TERM=xterm-256color
export repo="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd ../.. && pwd )"
WORKSPACE=${WORKSPACE:-$repo}

set -e -x
cd $WORKSPACE
sudo git clean -dxf
pwd
whoami
ls -la

srcdir=$WORKSPACE/src/HCFS
testdir=$WORKSPACE/tests

# Install dependencies
$WORKSPACE/utils/setup_dev_env.sh -vm unit_test
# Speedup compiling
. $WORKSPACE/utils/env_config.sh
sudo chown -R $USER:$USER $HOME/.ccache || :

# oclint-report.xml
#       OCLint with Bear
bear make -C $srcdir
/oclint-0.8.1/bin/oclint-json-compilation-database . -- -report-type pmd -o $WORKSPACE/oclint-report.xml || :
sed -i "s@file name=\"@&src/HCFS/@g" $WORKSPACE/oclint-report.xml

# cpd-result.xml
#        PMD's Copy/Paste Detector (CPD)
/pmd-bin-5.2.2/bin/run.sh cpd --minimum-tokens 100 --encoding UTF-8 --files $srcdir --format xml --language cpp > $WORKSPACE/cpd-result.xml || return_code=$?
if [[ "$return_code" != "" && "$return_code" != 4 ]]; then
	echo pmd returns unknown error code $return_code
	false
fi
sed -i "s@$WORKSPACE/@@g" $WORKSPACE/cpd-result.xml

# cloc-result.xml
#        Publish SLOCCount analysis results
cloc --by-file --xml --out=$WORKSPACE/cloc-result.xml $srcdir
sed -i "s@$WORKSPACE/@@g" $WORKSPACE/cloc-result.xml

# ccm-result.xml
#        Publish CCM analysis results (Cyclomatic Complexity)
mono /CCM.exe $srcdir /xml > $WORKSPACE/ccm-result.xml
sed -i "s@<file>/@<file>src/HCFS/@g" $WORKSPACE/ccm-result.xml

# Run unit test
cd $testdir/unit_test
./run_unittests

# hb_clint.xml
#         Cehck code style
$testdir/code_checking/hb_clint.py `find $srcdir -name '*.[ch]'` 2>&1 | tee $WORKSPACE/hb_clint.xml
sed -i "s@$WORKSPACE/@@g" $WORKSPACE/hb_clint.xml

# No report
#         Cehck code style
$testdir/code_checking/checkpatch.pl --terse --no-tree --no-signoff -f `find $srcdir -name '*.[ch]'` || :

# coverage.xml
#         Unit test coverage report
cd $testdir/unit_test
gcovr -x -r $srcdir . > $WORKSPACE/coverage.xml
sed -i "s@$WORKSPACE/@@g" $WORKSPACE/coverage.xml
gcovr -r $srcdir .
