#!/bin/bash
echo ======== ${BASH_SOURCE[0]} ========
echo docker-unittest-stylecheck-slave environment is required
export TERM=xterm-256color
export repo="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd ../.. && pwd )"
WORKSPACE=${WORKSPACE:-$repo}

set -e -x
cd $WORKSPACE
pwd
whoami
ls -la

srcdir=$WORKSPACE/src
testdir=$WORKSPACE/tests

# Install dependencies
$WORKSPACE/utils/setup_dev_env.sh -vm unit_test
# Speedup compiling
. $WORKSPACE/utils/env_config.sh
sudo chown -R $USER:$USER $HOME/.ccache || :

# Using OCLint with Bear
bear make -C $srcdir/HCFS
/oclint-0.8.1/bin/oclint-json-compilation-database . -- -report-type pmd -o oclint-report.xml -max-priority-1=0 -max-priority-2=50 -max-priority-3=100 || :
sed -i 's/file name="/&src\/HCFS\//g' oclint-report.xml

# PMD's Copy/Paste Detector (CPD)
sudo /pmd-bin-5.2.2/bin/run.sh cpd --minimum-tokens 100 --encoding UTF-8 --files $srcdir/ --format xml --language cpp > $WORKSPACE/cpd-result.xml || return_code=$?
if [[ "$return_code" != "" && "$return_code" != 4 ]]; then
	echo pmd returns unknown error code $return_code
	false
fi

# Publish SLOCCount analysis results
sudo cloc --by-file --xml --out=$WORKSPACE/cloc-result.xml $srcdir/HCFS/

# Publish CCM analysis results (Cyclomatic Complexity)
sudo mono /CCM.exe . /xml > $WORKSPACE/ccm-result.xml

# Run unit test
cd $testdir/unit_test
./run_unittests

# Cehck code style
$testdir/code_checking/hb_clint.py `find $srcdir -name '*.[ch]'` 2>&1 | tee $WORKSPACE/hb_clint.xml
$testdir/code_checking/checkpatch.pl --terse --no-tree --no-signoff -f `find $srcdir -name '*.[ch]'` || :

# Unit test coverage report
cd $testdir/unit_test
gcovr -x -r $srcdir . > $WORKSPACE/coverage.xml
gcovr -r $srcdir .
