#!/usr/bin/expect -f
#
# Create on 2011/07/26
# Author: Juitsung Hung
# Description:
#   destory remote hard drive.
#
set timeout 3
set HOSTADDR [lindex $argv 0]

spawn ssh root@$HOSTADDR
while {$timeout ne 0} {
  expect "password:" {
    send "deltacloud\r"
    expect "~#" {
      send "dd if=/dev/zero of=/dev/sda count=1 bs=512\r"
      expect "~#" {
        send "halt\r"
        expect "root@" {
          exit
        }
      }
    }
  }
}
exit
