#!/usr/bin/expect -f

set timeout 3
set SWITCHADDR [lindex $argv 0]

spawn telnet $SWITCHADDR
while {$timeout ne 0} {
  expect "User:" {
    send "admin\r"
    expect "Password:" {
      send "\r"
      expect ">" {
        send "en\r"
        expect "#" {
          send "clear arp-cache\r"
          expect "#" {
            send "clear mac-addr-table all\r"
            expect "#" {
              send "exit\r"
              exit
            }
          }
        }
      }
    }
  }
}
exit