#!/bin/bash

SNMPWALK=/usr/bin/snmpwalk
SNMPCOMMUNITY=public
SNMPVERSION=1
#SWITCHADDR=172.16.14.246
SWITCHADDR=10.129.7.230
SNMPWALKS="$SNMPWALK -c$SNMPCOMMUNITY -v$SNMPVERSION"
FDBTABLE=1.3.6.1.2.1.1.5

SWITCHNAME=`$SNMPWALK -c$SNMPCOMMUNITY -v$SNMPVERSION $SWITCHADDR $FDBTABLE| \
            sed "s/[=:\"]//g" | \
            awk '{print $3}'`
echo $SWITCHNAME
